packageExtensions:
  eslint-config-airbnb-typescript@*:
    peerDependencies:
      eslint: "*"
      eslint-plugin-import: "*"
      eslint-plugin-jsx-a11y: "*"
  node-fetch@*:
    dependencies:
      encoding: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"

pnpMode: strict

yarnPath: .yarn/releases/yarn-2.4.1.cjs
